//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bug
    {
        public int Id { get; set; }
        public string Problem { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserNameP { get; set; }
        public string UserNameR { get; set; }
        public Nullable<System.DateTime> DateResolved { get; set; }
    }
}
